version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      env: .env.development.local

  prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      env: .env
